# plot figure 1 in report
library(ggplot2)
OLS <- read.table("OLS_beta_cross.txt", header = FALSE, sep = "")
OLS_int <- apply(OLS, 2, function(x) quantile(x, probs = c(0.025, 0.5, 0.975), names =TRUE))
data_OLS <- data.frame(t(OLS_int))
data_OLS <- cbind(rep("OLS", dim(data_OLS)[1]), rownames(data_OLS), data_OLS)
colnames(data_OLS)[1:2] <- c("method", "parameter")
Ridge <- read.table("Ridge_beta_cross.txt", header = FALSE, sep = "")
Ridge_int <- apply(Ridge, 2, function(x) quantile(x, probs = c(0.25, 0.5, 0.75), names =TRUE))
data_Ridge <- data.frame(t(Ridge_int))
data_Ridge <- cbind(rep("Ridge", dim(data_Ridge)[1]), rownames(data_Ridge), data_Ridge)
colnames(data_Ridge)[1:2] <- c("method", "parameter")
Lasso <- read.table("Lasso_beta_cross.txt", header = FALSE, sep = "")
Lasso_int <- apply(Lasso, 2, function(x) quantile(x, probs = c(0.025, 0.5, 0.975), names =TRUE))
data_Lasso <- data.frame(t(Lasso_int))
data_Lasso <- cbind(rep("Lasso", dim(data_Lasso)[1]), rownames(data_Lasso), data_Lasso)
colnames(data_Lasso)[1:2] <- c("method", "parameter")

plot_data <- rbind(data_OLS, data_Ridge)
plot_data <- rbind(plot_data, data_Lasso)
colnames(plot_data)[3:5] <- c("Q1", "median", "Q3")

p <- ggplot(data = plot_data, aes(x = method, y = median))
p <- p + geom_bar(stat="identity", color="grey60", fill = "grey60", position=position_dodge())
p <- p + geom_errorbar(aes(ymin=Q1, ymax=Q3), width=.6, position=position_dodge(.9), cex = 2) 
#p <- p + facet_wrap( ~parameter, nrow = 21, ncol = 1, scales = "free_y")
#ggsave(filename = "parameters_int.png", plot = p, width = 2, height = 21, units = "in")

p <- p + facet_wrap( ~parameter, nrow = 7, ncol = 3, scales = "free_y")
p <- p + ylab(expression(beta))
ggsave(filename = "parameters_int.png", plot = p, width = 10, height = 14, units = "in")